---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mrms-user
  namespace: [@namespace]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mrms-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mrms-user
    namespace: [@namespace]
---
kind: Service
apiVersion: v1
metadata:
  name: mrms-svc
  namespace: [@namespace]
spec:
  type: NodePort
  ports:
    - name: "ssh"
      port: 10022
      targetPort: 9100
      nodePort: 30022
    - name: "mrms-servlet"
      port: 9200
      targetPort: 9200
      nodePort: 31920
  selector:
    app: mrms
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrms
  labels:
    app: mrms
  namespace: [@namespace]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mrms
  template:
    metadata:
      labels:
        app: mrms
    spec:
      serviceAccountName: mrms-user
      containers:
        - name: mrms
          image: [@registry_url]/ape/automl-mrms:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
          command: ["/bin/bash", "./mrms.sh"]
          env:
            - name: TZ
              value: Asia/Seoul
          volumeMounts:
            - name: timezone-config
              mountPath: /etc/localtime
            - name: automl-processing
              mountPath: [@app_dir]/data/processing
            - name: automl-storage
              mountPath: [@app_dir]/data/storage/ape
            - name: mrms-conf-v
              mountPath: [@app_dir]/app/ape/mrms/conf

        - name: mrms-sftp
          image: [@registry_url]/ape/sftp-server:1.0.0
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: timezone-config
              mountPath: /etc/localtime
            - name: automl-processing
              mountPath: [@app_dir]/data/processing
            - name: automl-storage
              mountPath: [@app_dir]/data/storage/ape

      volumes:
        - name: automl-processing
          hostPath:
            path: [@app_dir]/data/processing
        - name: automl-storage
          hostPath:
            path: [@app_dir]/data/storage/ape
        - name: timezone-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: mrms-conf-v
          configMap:
            name: mrms-conf
      nodeSelector:
        app: "true"
---
