---
kind: Service
apiVersion: v1
metadata:
  name: ape-storage-svc
  namespace: [@namespace]
spec:
  type: "LoadBalancer"
  ports:
    - name: "ssh"
      port: 10122
      targetPort: 22
  selector:
    app: ape-web
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ape-storage
  labels:
    app: ape-storage
  namespace: [@namespace]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ape-storage
  template:
    metadata:
      labels:
        app: ape-storage
    spec:
      containers:
        - name: storage-sftp
          image: [@registry_url]/ape/sftp-server:1.0.0
          ports:
          - containerPort: 22
          volumeMounts:
          - name: timezone-config
            mountPath: /etc/localtime
          - name: storage-upload
            mountPath: [@app_dir]/app/www/store/upload/

      volumes:
        - name: storage-upload
          hostPath:
            path: [@app_dir]/app/www/store/upload/
        - name: timezone-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul

      nodeSelector:
        storage: "true"
---
